### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by ziadagh** [itemic/rotacsufbo#5]
Hello, I am a bit new to this.

I am trying to Obfuscate my android library, in order to package it for customer delivery.
How can I selectively obfuscate my classes and methods (I may not want to obfuscate everything)?
How do I start using your library?
A small guide would be helpful.

**Comment by itemic** [comment]
Hi ziadagh,

this tool does not support selective obfuscation and is no longer in development as it was for a university course
